package com.debtulator.backend.sync;

public enum SyncErrorCode {
    INVALID_ENTITY_TYPE,
    INVALID_OPERATION,
    INVALID_PAYLOAD,
    BASE_VERSION_REQUIRED,
    VERSION_CONFLICT,
    ENTITY_ALREADY_EXISTS,
    ENTITY_NOT_FOUND,
    ENTITY_DELETED,
    IDEMPOTENCY_KEY_REUSED,
    MEMBER_IN_USE,
    MEMBER_LINKED,
    MEMBER_NOT_FOUND,
    CURRENCY_NOT_SUPPORTED,
    TEMPORARY_FAILURE
}

