spring:
  application:
    name: debtulator-backend

  web:
    error:
      include-message: never
      include-binding-errors: never
      include-stacktrace: never

server:
  port: ${PORT:8080}
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: never
