-- ============================================================================
-- Debtulator sync infrastructure
-- ============================================================================


-- ============================================================================
-- Data API grants
--
-- RLS controls which rows authenticated users may access.
-- GRANT controls whether the authenticated role can access the table at all.
-- ============================================================================

grant usage on schema public to authenticated;

grant select
on public.currencies
to authenticated;

grant select, insert, update
on public.profiles
to authenticated;

grant select, insert, update, delete
on public.members
to authenticated;

grant select, insert, update, delete
on public.debts
to authenticated;


-- ============================================================================
-- Sync changes
--
-- This is the durable replication stream consumed by devices.
--
-- sequence is intentionally generated by PostgreSQL. Devices NEVER generate
-- or compare timestamps to determine replication order.
-- ============================================================================

create table public.sync_changes (
  sequence bigint generated always as identity primary key,

  owner_user_id uuid not null
    references auth.users(id)
    on delete cascade,

  entity_type text not null,

  entity_id uuid not null,

  operation text not null,

  payload jsonb,

  changed_at timestamptz not null default now(),

  constraint sync_changes_entity_type_valid
    check (
      entity_type in ('member', 'debt')
    ),

  constraint sync_changes_operation_valid
    check (
      operation in ('upsert', 'delete')
    ),

  constraint sync_changes_payload_valid
    check (
      (
        operation = 'upsert'
        and payload is not null
      )
      or
      (
        operation = 'delete'
        and payload is null
      )
    )
);


create index sync_changes_owner_sequence_idx
  on public.sync_changes (
    owner_user_id,
    sequence
  );


alter table public.sync_changes
enable row level security;


create policy "sync_changes_select_own"
on public.sync_changes
for select
to authenticated
using (
  owner_user_id = (select auth.uid())
);


grant select
on public.sync_changes
to authenticated;


-- ============================================================================
-- Members change trigger
-- ============================================================================

create or replace function public.record_member_sync_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    insert into public.sync_changes (
      owner_user_id,
      entity_type,
      entity_id,
      operation,
      payload
    )
    values (
      old.owner_user_id,
      'member',
      old.id,
      'delete',
      null
    );

    return old;
  end if;

  insert into public.sync_changes (
    owner_user_id,
    entity_type,
    entity_id,
    operation,
    payload
  )
  values (
    new.owner_user_id,
    'member',
    new.id,
    'upsert',
    to_jsonb(new)
  );

  return new;
end;
$$;


create trigger members_record_sync_change
after insert or update or delete
on public.members
for each row
execute function public.record_member_sync_change();


-- ============================================================================
-- Debts change trigger
-- ============================================================================

create or replace function public.record_debt_sync_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    insert into public.sync_changes (
      owner_user_id,
      entity_type,
      entity_id,
      operation,
      payload
    )
    values (
      old.owner_user_id,
      'debt',
      old.id,
      'delete',
      null
    );

    return old;
  end if;

  insert into public.sync_changes (
    owner_user_id,
    entity_type,
    entity_id,
    operation,
    payload
  )
  values (
    new.owner_user_id,
    'debt',
    new.id,
    'upsert',
    to_jsonb(new)
  );

  return new;
end;
$$;


create trigger debts_record_sync_change
after insert or update or delete
on public.debts
for each row
execute function public.record_debt_sync_change();


-- ============================================================================
-- Realtime
--
-- Realtime is only an invalidation/wakeup mechanism.
-- sync_changes itself remains the durable replication source.
-- ============================================================================

alter publication supabase_realtime
add table public.sync_changes;